#!/bin/sh
set -e
if [ "$1" = remove ] || [ "$1" = deconfigure ]; then
  systemctl stop contactsync-automation.service >/dev/null 2>&1 || true
  systemctl stop contactsync-professional.service >/dev/null 2>&1 || true
fi
exit 0
